version: "3.8"

services:
    app:
        build: .
        working_dir: /usr/src/app
        env_file:
            - .env
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        command: yarn start
        ports:
            - "5000:5000"
        environment:
            - NODE_ENV=development
            - PORT=5000
        depends_on:
            - mongo
            - redis

    mongo:
        image: mongo:6
        ports:
            - "27018:27017"
        volumes:
            - mongo-data:/data/db

    redis:
        image: redis:7
        ports:
            - "6379:6379"

volumes:
    mongo-data:
